### ISSUE TITLE
Export wildstar from dependencies not working

### ISSUE THREAD

**Issue by jorenbroekema** [divriots/backlight.dev#3] opened 2021-08-09 09:07 UTC
### Reproduction steps

1. Go to any backlight.dev repository
2. Create a file, `core/index.js`:
    ```js
    export * from '@lion/core'; // can be any dependency that has multiple exports
    ```
3. Try to import from core/index.js in a different file:
    ```js
    import { LitElement } from '~/core'; // error
    ```
4. See error in console

### Current Behavior

- ❌ **I cannot get imports from a local module that re-exports everything from a dependency module on backlight.**
- ✔️ I can get imports from a local module that re-exports everything from a dependency module on my own local environment not using packd but using regular NPM.  
- ✔️ I can get import from a local module that re-exports everything from another local module.  

### Expected Behavior

- ✔️ I **can get imports from a local module that re-exports everything from a dependency module on backlight.**
- ✔️ I can get imports from a local module that re-exports everything from a dependency module on my own local environment not using packd but using regular NPM.  
- ✔️ I can get import from a local module that re-exports everything from another local module.  ng from another local module.

### Link to the design system

https://backlight.dev/edit/5vtJtbY04aoD1dGKcsu1

### What browser(s) are you seeing the problem on?

Chrome

**Comment by muryoh** [comment] 2021-08-11 09:25
Hard to fix with the current compiler implementation
The up-coming one may fix it by design, maybe we can see then

**Comment by muryoh** [comment] 2021-09-27 21:09
As stated before, won't be fixed with the previous compiler implem but just confirmed it is supported in the new one :+1:

**Closed by muryoh** 2021-09-27 21:09 UTC
Labels: bug

**Comment by jorenbroekema** [comment] 2021-09-28 08:02
Yo that's super awesome!! Will make simba a lot more usable, gonna do some patches this week then
